name: axilo
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_storage: ^2.1.1
  dio: ^5.8.0+1
  path: ^1.9.0
  path_provider: ^2.1.5
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  auto_size_text: ^3.0.0
  get: ^4.7.2
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.1.0
  flutter_typeahead: ^5.2.0
  intl: ^0.20.2
  uuid: ^4.5.1
  dotted_border: ^2.1.0
  stripe_android: 11.4.0
  stripe_ios: 11.4.0
  stripe_platform_interface: 11.4.0
  flutter_stripe: 11.4.0
  flutter_dotenv: ^5.2.1
  location: ^7.0.1
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.10.1
  geolocator: ^14.0.1
  loading_animation_widget: ^1.3.0
  image_picker: ^1.1.2
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  cached_network_image: ^3.4.1
  firebase_crashlytics: ^4.3.6
  # flutter_map_location_marker: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  min_sdk_android: 21
  image_path: "assets/image/launcher/icon.png"
  adaptive_icon_background: "#7849e3"

dependency_overrides:
  geolocator_android: 4.6.1

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/image/launcher/
    - assets/map_style/light_map.json
    - assets/image/car/
    - assets/image/icons/
    - assets/image/service_icons/
    - assets/image/home/
    - assets/image/appbar/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
    - family: OswaldRegular
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf